### ISSUE TITLE
登録しても一覧が表示されないRSSがあります

### ISSUE THREAD

**Issue by MakotoTAKEHARA** [maiyama18/Riverside#41]
実行環境:iPad mini  iPad OS 17.4.1 
アプリのバージョン:1.1.0

一覧が表示されないRSS
[朝日新聞](https://www.asahi.com/rss/asahi/newsheadlines.rdf)
[AV watch](https://av.watch.impress.co.jp/data/rss/1.0/avw/feed.rdf)
[トイロ公式ブログ](https://toiroiro.blog.jp/index.rdf)

はてなblogのは取得できています。

**Comment by maiyama18** [comment]
@MakotoTAKEHARA ご連絡ありがとうございます！ https://github.com/maiyama18/Riverside/pull/43 にて修正しました。近いうちに実施する次のリリースにて直ると思うのでこの issue は close しますが、何かあれば reopen お願いします 🙏

**Comment by maiyama18** [comment]
最新バージョンの 1.2.0 にて解消されていそうです。

**Comment by MakotoTAKEHARA** [comment]
1.2.0で取得できるようになりました。対応していただきありがとうございます。
