### ISSUE TITLE
streamを開いてからアプリが強制終了するようになりました

### ISSUE THREAD

**Issue by MakotoTAKEHARA** [maiyama18/Riverside#48]
実行環境:iPad mini iPad OS 17.4.1
アプリのバージョン:1.2.0

現象:feedとsettingを見ているときは正常でしたが、streamを表示させた後数秒でアプリが強制終了するようになりました。
以降はアプリを何回か立ち上げなおしても数秒で強制終了します。
streamに表示された件数は100でした。

アプリのクラッシュログを添付します。

[Riverside-2024-04-29-124953.ips.zip](https://github.com/maiyama18/Riverside/files/15145015/Riverside-2024-04-29-124953.ips.zip)

**Comment by maiyama18** [comment]
遅くなって申し訳ありません。クラッシュログからデータベース周りでクラッシュしていそうなことはわかるのですが、具体的な原因はわからず、手元でも再現しません。データ取得がそもそも重い問題もあるので、ロジックをサーバに移動することでクラッシュが発生しづらいようにならないか検討してみようと思います。

**Comment by MakotoTAKEHARA** [comment]
調査していただきありがとうございます。
追加したRSSのどれかが悪さをしているのかと思い一度アンインストールして再度インストールし1つずつ調べようとしたのですが、再インストールすると前回追加したものが一瞬表示され同様にクラッシュしました。
インストール直後に起動したときに前回の情報が残っていたらそれを引き続き使うか、それとも初期化して使うか選択できる方法はあるでしょうか。

**Comment by maiyama18** [comment]
色々と試していただきありがとうございます。このアプリではデータを iCloud 同期しているため、端末でアプリをアンインストールしても iCloud にデータが残っている状態になっています。

設定アプリの「Apple ID、 iCloud+、メディアと購入」 > 「iCloud」 > 「iCloud を使用しているアプリ」から Riverside のトグルを一度オフにしてから再度オンにしていただけると初期化ができると思います。お手数ですがお試しいただけますと幸いです。

**Comment by MakotoTAKEHARA** [comment]
報告が遅くなり申し訳ありません。結局どれがいけないのかわからなかったのですが、先日のアップデート1.3.0で正常に見られるようになりました。ありがとうございます。問題が解決したのでこれで本issueを閉じさせていただきます。

**Comment by maiyama18** [comment]
こちらこそご連絡が遅れてすみません 🙏 推測ですが、これまでアプリ側で頑張ってフィードを１つ１つデータベースに保存していたことによりクラッシュが起きていたのが 1.3.0 でサーバを通じてフィードをまとめて取得するようにしたことにより直ったのだと思います。ありがとうございました！
